version: '2.2'
services:
  identity-admin:
    extends:
      file: docker-compose.yml
      service: identity-admin
    build:
      dockerfile: Skoruba.IdentityServer4.Admin/Dockerfile
      context: ./IdentityServer4.Admin/src
    networks:
      - identity-network
    links:
      - identity
    depends_on:
      - identity

  identity:
    extends:
      file: docker-compose.yml
      service: identity
    build:
      dockerfile: Skoruba.IdentityServer4.STS.Identity/Dockerfile
      context: ./IdentityServer4.Admin/src
    networks:
      - identity-network

networks:
  identity-network:
    driver: bridge
